version: '3'
services:
  nukkit:
    image: nukkit
    restart: always  
    ports:
      - "19132:19132/udp"
    volumes:
       - ./data:/data
       - ./app:/app:ro
    stdin_open: true
    tty: true
