version: '3'
services:
  minecraft-server:
    image: minecraft-server 
    restart: always  
    ports:
      - "25565:25565/tcp"
      - "19132:19132/udp"
    volumes:
       - ./data:/data
       - ./app:/app:ro
    stdin_open: true
    tty: true
